language: ruby
sudo: false
cache: bundler

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - jruby-9.1.5.0

gemfile:
  - gemfiles/Gemfile-rails-5.0
  - gemfiles/Gemfile-rails-5.1
  - gemfiles/Gemfile-rails-master
  - Gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-rails-master

notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
